name: tteokguk-please frontend continuous developments
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.19.0"
          cache: "pnpm"

      - name: Install pnpm dependencies
        run: pnpm install

      - name: React build
        run: pnpm run build
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_KAKAO_API_KEY: ${{ secrets.VITE_KAKAO_API_KEY }}
          VITE_KAKAO_CLIENT_SECRET: ${{ secrets.VITE_KAKAO_CLIENT_SECRET }}
          VITE_KAKAO_LOGIN_URI: ${{ secrets.VITE_KAKAO_LOGIN_URI }}
          VITE_KAKAO_REDIRECT_URI: ${{ secrets.VITE_KAKAO_REDIRECT_URI }}
          VITE_GA_TRACKING_ID: ${{ secrets.VITE_GA_TRACKING_ID }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DNS }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        env:
          BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          aws s3 rm s3://$BUCKET_NAME/assets/ --recursive
          aws s3 sync ./dist s3://$BUCKET_NAME

      - name: CloudFront Invalidation
        env:
          CLOUD_FRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
        run: aws cloudfront create-invalidation --distribution-id $CLOUD_FRONT_ID --paths /*
